name: Python Application

on:
  push:
    branches:
      - main  # oder der Name des Branches, den du verwenden möchtest
  pull_request:
    branches:
      - main  # oder der Name des Branches, gegen den PRs gemacht werden

jobs:
  test:
    runs-on: ubuntu-latest  # Der Workflow wird auf einem Ubuntu-Runner ausgeführt

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Lädt dein Repository herunter

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Stelle sicher, dass die richtige Python-Version verwendet wird

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installiere die Python-Abhängigkeiten

    - name: Run tests
      run: |
        pytest  # Führt die Tests aus (stellt sicher, dass pytest in requirements.txt ist)
